// <auto-generated />
using CoopShopInfos.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CoopShopInfos.Migrations
{
    [DbContext(typeof(CoopShopInfosContext))]
    [Migration("20171201083356_Categories")]
    partial class Categories
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoopShopInfos.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryName");

                    b.Property<string>("Description");

                    b.Property<int?>("ShopId");

                    b.HasKey("CategoryId");

                    b.HasIndex("ShopId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("CoopShopInfos.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(13);

                    b.Property<int?>("CategoryId");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<float>("Qauntity");

                    b.Property<int>("Unit");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("CoopShopInfos.Models.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ShopAddress")
                        .HasMaxLength(100);

                    b.Property<string>("ShopCity")
                        .HasMaxLength(100);

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ShopPhoneNumber");

                    b.Property<string>("ShopPostCode")
                        .HasMaxLength(5);

                    b.HasKey("ShopId");

                    b.ToTable("Shop");
                });

            modelBuilder.Entity("CoopShopInfos.Models.ShopProduct", b =>
                {
                    b.Property<int>("ShopId");

                    b.Property<int>("ProductId");

                    b.Property<decimal>("Price");

                    b.HasKey("ShopId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ShopProduct");
                });

            modelBuilder.Entity("CoopShopInfos.Models.Category", b =>
                {
                    b.HasOne("CoopShopInfos.Models.Shop")
                        .WithMany("Categories")
                        .HasForeignKey("ShopId");
                });

            modelBuilder.Entity("CoopShopInfos.Models.Product", b =>
                {
                    b.HasOne("CoopShopInfos.Models.Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("CoopShopInfos.Models.ShopProduct", b =>
                {
                    b.HasOne("CoopShopInfos.Models.Product", "Product")
                        .WithMany("ShopProduct")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoopShopInfos.Models.Shop", "Shop")
                        .WithMany("ShopProduct")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
