// <auto-generated />
using CoopShopInfos.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CoopShopInfos.Migrations
{
    [DbContext(typeof(CoopShopInfosContext))]
    [Migration("20171207102824_CategoryNavigationProperty")]
    partial class CategoryNavigationProperty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoopShopInfos.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryName");

                    b.Property<string>("Description");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("CoopShopInfos.Models.CategoryProduct", b =>
                {
                    b.Property<int>("CategoryId");

                    b.Property<int>("ProductId");

                    b.HasKey("CategoryId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CategoryProduct");
                });

            modelBuilder.Entity("CoopShopInfos.Models.Price", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("PriceAmount");

                    b.HasKey("PriceId");

                    b.ToTable("Price");
                });

            modelBuilder.Entity("CoopShopInfos.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(13);

                    b.Property<string>("ImageUrl");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<float>("Quantity");

                    b.Property<int>("Unit");

                    b.HasKey("ProductId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("CoopShopInfos.Models.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ShopAddress")
                        .HasMaxLength(100);

                    b.Property<string>("ShopCity")
                        .HasMaxLength(100);

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ShopPhoneNumber");

                    b.Property<string>("ShopPostCode")
                        .HasMaxLength(5);

                    b.HasKey("ShopId");

                    b.ToTable("Shop");
                });

            modelBuilder.Entity("CoopShopInfos.Models.ShopProduct", b =>
                {
                    b.Property<int>("ShopId");

                    b.Property<int>("ProductId");

                    b.Property<int>("PriceId");

                    b.Property<DateTime>("PriceDateTime");

                    b.HasKey("ShopId", "ProductId", "PriceId");

                    b.HasIndex("PriceId");

                    b.HasIndex("ProductId");

                    b.ToTable("ShopProduct");
                });

            modelBuilder.Entity("CoopShopInfos.Models.CategoryProduct", b =>
                {
                    b.HasOne("CoopShopInfos.Models.Category", "Category")
                        .WithMany("CategoryProduct")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoopShopInfos.Models.Product", "Product")
                        .WithMany("CategoryProduct")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoopShopInfos.Models.ShopProduct", b =>
                {
                    b.HasOne("CoopShopInfos.Models.Price", "Price")
                        .WithMany("ShopProduct")
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoopShopInfos.Models.Product", "Product")
                        .WithMany("ShopProduct")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoopShopInfos.Models.Shop", "Shop")
                        .WithMany("ShopProduct")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
